server:
  port: 8082

spring:
  application:
    name: inventory-service
  
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 2000ms
  
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderEvent:com.example.shared.event.OrderEvent

# Kafka Topics
kafka:
  topics:
    order-events: order-events
    inventory-check-results: inventory-check-results

# Logging
logging:
  level:
    com.example.inventoryservice: DEBUG
    org.springframework.kafka: INFO

